apiVersion: k8s.ovn.org/v1
kind: EgressIP
metadata:
  name: egressip-test
spec:
  egressIPs:
    - 192.168.0.145
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: test
  podSelector:
    matchLabels:
      app: validator 

