---
apiVersion: v1
kind: Namespace
metadata:
  name: monitor-eip
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: validator
  name: monitor-eip
  namespace: monitor-eip
spec:
  endpoints:
    - interval: 30s
      port: metrics
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      scheme: http
  jobLabel: app
  namespaceSelector:
    matchNames:
      - monitor-eip
  selector:
    matchLabels:
      app: validator
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: validator
  name: monitor-eip
  namespace: monitor-eip
spec:
  selector:
    app: validator
  clusterIP: None
  publishNotReadyAddresses: false
  ports:
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: 8080
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-k8s
  namespace: monitor-eip
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-k8s
  namespace: monitor-eip
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-k8s
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: openshift-monitoring