apiVersion: v1
kind: Pod
metadata:
  name: eip-monitor
  namespace: test
  labels:
    app: validator
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: eip-validator
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    image: quay.io/mkennell/eip-checker:latest
    imagePullPolicy: Always
    env:
    - name: EXT_SERVER_HOST
      value: "192.168.0.155"
    - name: EXT_SERVER_PORT
      value: "9002"
    - name: EGRESS_IPS
      value: "192.168.0.145"
    - name: DELAY_BETWEEN_START_REQ_SEC 
      value: "1"
    - name: REQ_START_TIMEOUT_SEC
      value: "1"
    - name: DELAY_BETWEEN_REQ_SEC
      value: "10"
    - name: REQ_TIMEOUT_SEC
      value: "5"
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    ports:
    - containerPort: 8080
      name: metrics
    resources:
      requests:
        cpu: "50m"

