---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: eip-validator
  namespace: test
spec:
  selector:
    matchLabels:
      app: validator
  podMetricsEndpoints:
  - port: metrics
    interval: 15s
    scheme: http
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-k8s
  namespace: test
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-k8s
  namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-k8s
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: openshift-monitoring
    
